const types = {
  EDIT_ABOUT_ME: "EDIT_ABOUT_ME",
  ADD_NEW_DEGREE: "ADD_NEW_DEGREE",
  DELETE_DEGREE: "DELETE_DEGREE",
  ADD_NEW_SKILL: "ADD_NEW_SKILL",
  DELETE_SKILL: "DELETE_SKILL",
};

export default types;
